### ISSUE TITLE
Returns Module Error

### ISSUE THREAD

**Issue by mhmmdd** [beingsagir/play-java-spring-data-jpa#1]
```
Cannot load module
Module [SpringDataJpaModule] cannot be instantiated
```

**Comment by beingsagir** [comment]
**Please collect the last update**. If problem still there, make sure you have added right credential of your DB in the setting. Reopen this issue if it is not solved.

**Comment by mhmmdd** [comment]
Sorry, when I added postgresql dependency I mistake in the application.conf file. It works properly.
